import {
  CellStyleModule,
  ClientSideRowModelApiModule,
  ClientSideRowModelModule,
  ColumnApiModule,
  ColumnAutoSizeModule,
  ColumnHoverModule,
  CsvExportModule,
  DateFilterModule,
  HighlightChangesModule,
  LocaleModule,
  ModuleRegistry,
  NumberFilterModule,
  PinnedRowModule,
  QuickFilterModule,
  RowSelectionModule,
  TextFilterModule,
  TooltipModule,
} from "ag-grid-community";

// Registrar al cargar las tablas, después de entrar al panel.
ModuleRegistry.registerModules([
  CellStyleModule,
  ClientSideRowModelApiModule,
  ClientSideRowModelModule,
  ColumnApiModule,
  ColumnAutoSizeModule,
  ColumnHoverModule,
  CsvExportModule,
  DateFilterModule,
  HighlightChangesModule,
  LocaleModule,
  NumberFilterModule,
  PinnedRowModule,
  QuickFilterModule,
  RowSelectionModule,
  TextFilterModule,
  TooltipModule,
]);

